window.ICS=window.ICS||{};
ICS.MUSTER={
rueckzug:{name:"Rückzugsmuster",begriffe:["ich ziehe mich zurueck","ziehe mich zurueck","mich zurueckziehen","zurueckziehen","rueckzug","gehe auf abstand","mache dicht","sage nichts mehr","isoliere mich","will meine ruhe","brauche abstand"],spiegel:"Rückzug kann kurzfristig schützen, verhindert aber manchmal, dass deine wirklichen Bedürfnisse sichtbar werden.",fragen:["Ziehst du dich eher zurück, um dich zu schützen, einen Konflikt zu vermeiden oder weil du dich überfordert fühlst?","Wovor schützt dich dieser Rückzug konkret?","Welches Bedürfnis bleibt dadurch unausgesprochen?","Was wäre ein kleiner sicherer Schritt zurück in Verbindung?"],innerCode:"Du darfst dich schützen, ohne dich vollständig unsichtbar zu machen.",bodyCode:"Spüre, wo dein Körper eng wird, wenn Nähe oder Konflikt entsteht.",actionCode:"Sprich heute einen ehrlichen Satz aus, den du sonst zurückhalten würdest."},
harmonie:{name:"Harmoniemuster",begriffe:["will keinen streit","konflikt vermeiden","vermeide konflikte","ich vermeide konflikte","hauptsache harmonie","sage lieber nichts","will niemanden verletzen","halte den frieden"],spiegel:"Harmonie kann Frieden schaffen. Unechte Harmonie entsteht jedoch, wenn Wahrheit dauerhaft verschwiegen wird.",fragen:["Welchen Konflikt versuchst du gerade zu vermeiden?","Was bleibt dadurch unausgesprochen?","Welche Wahrheit lässt sich klar und respektvoll ausdrücken?","Was wäre ein friedlicher, aber ehrlicher nächster Schritt?"],innerCode:"Echte Harmonie braucht Wahrheit, nicht Schweigen.",bodyCode:"Spüre deinen Hals und Brustraum, bevor du etwas Wichtiges aussprichst.",actionCode:"Formuliere einen ehrlichen Satz ohne Vorwurf."},
kontrolle:{name:"Kontrollmuster",begriffe:["alles kontrollieren","nicht loslassen","alles im griff","mache lieber alles selbst","kontrolle verlieren","muss wissen was passiert"],spiegel:"Kontrolle versucht häufig, Unsicherheit zu reduzieren und kostet gleichzeitig viel Kraft.",fragen:["Was befürchtest du, könnte geschehen, wenn du einen Teil der Kontrolle abgeben würdest?","Welche Erfahrung hat dir beigebracht, dass du alles selbst sichern musst?","Was liegt tatsächlich in deiner Verantwortung – und was nicht?","Was könntest du heute bewusst nicht kontrollieren?"],innerCode:"Sicherheit entsteht nicht nur durch Kontrolle, sondern auch durch Vertrauen in deine Reaktionsfähigkeit.",bodyCode:"Löse bewusst Hände, Kiefer und Schultern.",actionCode:"Gib heute eine kleine Aufgabe oder Entscheidung bewusst ab."},
perfektionismus:{name:"Perfektionsmuster",begriffe:["muss perfekt","darf keinen fehler","nie gut genug","muss es besser","alles richtig machen","perfektion"],spiegel:"Perfektionismus schützt oft vor Kritik, Scham oder Ablehnung.",fragen:["Was würde passieren, wenn dein Ergebnis gut und stimmig wäre – aber nicht perfekt?","Wessen Anerkennung versuchst du durch Perfektion zu erhalten?","Was kostet dich dieser Anspruch?","Wie sähe eine gute 80-Prozent-Lösung aus?"],innerCode:"Dein Wert wächst nicht durch Fehlerfreiheit.",bodyCode:"Atme aus und erlaube deinem Körper, für einen Moment nicht leisten zu müssen.",actionCode:"Schließe heute eine Aufgabe bewusst bei 80 Prozent ab."},
anpassung:{name:"Anpassungsmuster",begriffe:["sage immer ja","kann nicht nein sagen","passe mich an","mache es allen recht","stelle mich hinten an","will niemanden enttaeuschen"],spiegel:"Anpassung kann Zugehörigkeit sichern, während die eigene Wahrheit immer leiser wird.",fragen:["Was würdest du sagen oder entscheiden, wenn deine Bedürfnisse genauso wichtig wären wie die der anderen?","Welche Reaktion anderer befürchtest du bei einem Nein?","Wo überschreitest du regelmäßig deine eigene Grenze?","Welches kleine Nein wäre heute ein Ja zu dir?"],innerCode:"Zugehörigkeit, die Selbstaufgabe verlangt, ist keine echte Verbindung.",bodyCode:"Spüre, wie dein Körper auf ein ehrliches Ja und auf ein erzwungenes Ja reagiert.",actionCode:"Formuliere heute eine klare, respektvolle Grenze."},
vermeidung:{name:"Vermeidungsmuster",begriffe:["schiebe es auf","vermeide es","gehe dem aus dem weg","ignoriere es","mache es spaeter","prokrastiniere"],spiegel:"Vermeidung entlastet kurzfristig, hält die Belastung aber häufig aufrecht.",fragen:["Was genau macht den ersten Schritt unangenehm?","Welche Befürchtung steckt hinter dem Aufschieben?","Was kostet dich das weitere Vermeiden?","Was wäre der kleinstmögliche Schritt für heute?"],innerCode:"Du musst nicht die ganze Aufgabe bewältigen. Du brauchst nur den ersten ehrlichen Schritt.",bodyCode:"Nimm drei ruhige Atemzüge und richte den Blick nur auf die nächsten fünf Minuten.",actionCode:"Arbeite heute genau fünf Minuten an dem vermiedenen Thema."},
leistung:{name:"Leistungs- und Funktionsmuster",begriffe:["muss funktionieren","muss leisten","darf nicht ausfallen","muss weitermachen","keine pause","muss stark sein","funktioniere nur noch"],spiegel:"Leistung kann Anerkennung und Sicherheit geben. Problematisch wird sie, wenn dein Wert nur noch davon abhängt.",fragen:["Wer wärst du in diesem Moment, wenn du nichts beweisen müsstest?","Was glaubst du zu verlieren, wenn du nicht funktionierst?","Welche Körpersignale ignorierst du?","Welche Form von Ruhe wäre heute verantwortungsvoll?"],innerCode:"Du bist nicht nur wertvoll, wenn du funktionierst.",bodyCode:"Lege eine Hand auf den Brustkorb und erlaube dir drei Minuten ohne Aufgabe.",actionCode:"Plane heute eine bewusste Pause, die nicht verdient werden muss."},
anerkennung:{name:"Anerkennungsmuster",begriffe:["brauche bestaetigung","will anerkennung","was andere denken","allen gefallen","gelobt werden","will gesehen werden"],spiegel:"Der Wunsch nach Anerkennung ist menschlich. Er wird belastend, wenn die eigene Bewertung vollständig von außen abhängt.",fragen:["Von wem wünschst du dir besonders Anerkennung?","Was glaubst du, würde diese Anerkennung über deinen Wert beweisen?","Was erkennst du selbst heute an dir an?","Welche Entscheidung wäre unabhängig von der Meinung anderer stimmig?"],innerCode:"Äußere Anerkennung darf dich berühren, aber sie definiert nicht deinen Wert.",bodyCode:"Richte dich auf und nimm deinen Platz bewusst ein.",actionCode:"Notiere heute drei Dinge, die du selbst an dir anerkennst."},
verantwortung:{name:"Überverantwortungsmuster",begriffe:["fuer alles verantwortlich","muss mich um alles kuemmern","alles haengt an mir","rette alle","kuemmere mich um jeden","trage alles"],spiegel:"Verantwortung gibt Halt. Überverantwortung lässt dich jedoch Lasten tragen, die anderen gehören.",fragen:["Welche Verantwortung gehört wirklich zu dir?","Was übernimmst du für andere, obwohl sie es selbst tragen könnten?","Was befürchtest du, wenn du nicht eingreifst?","Welche Last könntest du heute zurückgeben?"],innerCode:"Du darfst unterstützen, ohne das Leben anderer zu tragen.",bodyCode:"Spüre bewusst deine Schultern und stelle dir vor, fremde Lasten abzulegen.",actionCode:"Übernimm heute eine Aufgabe bewusst nicht, die nicht deine ist."},
gedankenspirale:{name:"Gedankenspirale",begriffe:["denke staendig nach","komme aus dem denken nicht raus","gedanken kreisen","grueble","kopf hoert nicht auf","zu viele gedanken"],spiegel:"Dein Denken versucht möglicherweise, durch Analyse Sicherheit herzustellen.",fragen:["Welche eine Frage wiederholt sich in deinem Kopf?","Welche Antwort suchst du, die gerade nicht durch weiteres Denken entsteht?","Was ist Fakt – und was ist Befürchtung?","Welche körperliche Handlung bringt dich zurück in den Moment?"],innerCode:"Nicht jeder Gedanke braucht eine Lösung.",bodyCode:"Benenne fünf Dinge, die du siehst, vier, die du fühlst, und drei, die du hörst.",actionCode:"Schreibe den wichtigsten Gedanken auf und entscheide, ob heute eine Handlung möglich ist."}
};
ICS.musterErkennen=text=>ICS.bestesErgebnis(text,ICS.MUSTER);
ICS.musterErkennenAlle=text=>ICS.ergebnisse(text,ICS.MUSTER).slice(0,3);
