window.ICS=window.ICS||{};
ICS.MUSTER={
rueckzug:{name:"Rückzugsmuster",regeln:[/\bzieh(?:e|st|t|en)?\b.*\bzurueck\b/,/\bzurueckzieh/,/\brueckzug\b/,/\babstand\b/,/\bmache dicht\b/,/\bisoliere mich\b/],spiegel:"Rückzug kann kurzfristig schützen, verhindert aber manchmal, dass deine wirklichen Bedürfnisse sichtbar werden.",fragen:["Ziehst du dich eher zurück, um dich zu schützen, einen Konflikt zu vermeiden oder weil du dich überfordert fühlst?","Wovor schützt dich dieser Rückzug konkret?","Welches Bedürfnis bleibt dadurch unausgesprochen?","Was wäre ein kleiner sicherer Schritt zurück in Verbindung?"],innerCode:"Du darfst dich schützen, ohne dich vollständig unsichtbar zu machen.",bodyCode:"Spüre, wo dein Körper eng wird, wenn Nähe oder Konflikt entsteht.",actionCode:"Sprich heute einen ehrlichen Satz aus, den du sonst zurückhalten würdest."},
harmonie:{name:"Harmoniemuster",regeln:[/\bvermeide\b.*\bkonflikt/,/\bkonflikt\w*\b.*\bvermeide/,/\bkeinen streit\b/,/\bhauptsache harmonie\b/,/\bsage lieber nichts\b/,/\bniemanden verletzen\b/],spiegel:"Harmonie kann Frieden schaffen. Unechte Harmonie entsteht jedoch, wenn Wahrheit dauerhaft verschwiegen wird.",fragen:["Welchen Konflikt versuchst du gerade zu vermeiden?","Was bleibt dadurch unausgesprochen?","Welche Wahrheit lässt sich klar und respektvoll ausdrücken?","Was wäre ein friedlicher, aber ehrlicher nächster Schritt?"],innerCode:"Echte Harmonie braucht Wahrheit, nicht Schweigen.",bodyCode:"Spüre deinen Hals und Brustraum, bevor du etwas Wichtiges aussprichst.",actionCode:"Formuliere einen ehrlichen Satz ohne Vorwurf."},
kontrolle:{name:"Kontrollmuster",regeln:[/\bkontrollier/,/\bnicht loslassen\b/,/\balles im griff\b/,/\balles selbst\b/],spiegel:"Kontrolle versucht häufig, Unsicherheit zu reduzieren und kostet gleichzeitig viel Kraft.",fragen:["Was befürchtest du, könnte geschehen, wenn du einen Teil der Kontrolle abgeben würdest?","Welche Erfahrung hat dir beigebracht, dass du alles selbst sichern musst?","Was liegt tatsächlich in deiner Verantwortung – und was nicht?","Was könntest du heute bewusst nicht kontrollieren?"],innerCode:"Sicherheit entsteht nicht nur durch Kontrolle, sondern auch durch Vertrauen in deine Reaktionsfähigkeit.",bodyCode:"Löse bewusst Hände, Kiefer und Schultern.",actionCode:"Gib heute eine kleine Aufgabe oder Entscheidung bewusst ab."},
perfektionismus:{name:"Perfektionsmuster",regeln:[/\bperfekt/,/\bkeinen fehler\b/,/\bnie gut genug\b/,/\balles richtig\b/],spiegel:"Perfektionismus schützt oft vor Kritik, Scham oder Ablehnung.",fragen:["Was würde passieren, wenn dein Ergebnis gut und stimmig wäre – aber nicht perfekt?","Wessen Anerkennung versuchst du durch Perfektion zu erhalten?","Was kostet dich dieser Anspruch?","Wie sähe eine gute 80-Prozent-Lösung aus?"],innerCode:"Dein Wert wächst nicht durch Fehlerfreiheit.",bodyCode:"Atme aus und erlaube deinem Körper, für einen Moment nicht leisten zu müssen.",actionCode:"Schließe heute eine Aufgabe bewusst bei 80 Prozent ab."},
anpassung:{name:"Anpassungsmuster",regeln:[/\bsage immer ja\b/,/\bnicht nein sagen\b/,/\bpasse mich an\b/,/\ballen recht\b/,/\bhinten an\b/],spiegel:"Anpassung kann Zugehörigkeit sichern, während die eigene Wahrheit immer leiser wird.",fragen:["Was würdest du sagen oder entscheiden, wenn deine Bedürfnisse genauso wichtig wären wie die der anderen?","Welche Reaktion anderer befürchtest du bei einem Nein?","Wo überschreitest du regelmäßig deine eigene Grenze?","Welches kleine Nein wäre heute ein Ja zu dir?"],innerCode:"Zugehörigkeit, die Selbstaufgabe verlangt, ist keine echte Verbindung.",bodyCode:"Spüre, wie dein Körper auf ein ehrliches Ja und auf ein erzwungenes Ja reagiert.",actionCode:"Formuliere heute eine klare, respektvolle Grenze."},
vermeidung:{name:"Vermeidungsmuster",regeln:[/\bschiebe\b.*\bauf\b/,/\bvermeide es\b/,/\bgehe dem aus dem weg\b/,/\bignoriere\b/,/\bspaeter\b/],spiegel:"Vermeidung entlastet kurzfristig, hält die Belastung aber häufig aufrecht.",fragen:["Was genau macht den ersten Schritt unangenehm?","Welche Befürchtung steckt hinter dem Aufschieben?","Was kostet dich das weitere Vermeiden?","Was wäre der kleinstmögliche Schritt für heute?"],innerCode:"Du musst nicht die ganze Aufgabe bewältigen. Du brauchst nur den ersten ehrlichen Schritt.",bodyCode:"Nimm drei ruhige Atemzüge und richte den Blick nur auf die nächsten fünf Minuten.",actionCode:"Arbeite heute genau fünf Minuten an dem vermiedenen Thema."},
leistung:{name:"Leistungs- und Funktionsmuster",regeln:[/\bmuss funktionieren\b/,/\bfunktioniere nur noch\b/,/\bmuss leisten\b/,/\bkeine pause\b/,/\bmuss stark sein\b/],spiegel:"Leistung kann Anerkennung und Sicherheit geben. Problematisch wird sie, wenn dein Wert nur noch davon abhängt.",fragen:["Wer wärst du in diesem Moment, wenn du nichts beweisen müsstest?","Was glaubst du zu verlieren, wenn du nicht funktionierst?","Welche Körpersignale ignorierst du?","Welche Form von Ruhe wäre heute verantwortungsvoll?"],innerCode:"Du bist nicht nur wertvoll, wenn du funktionierst.",bodyCode:"Lege eine Hand auf den Brustkorb und erlaube dir drei Minuten ohne Aufgabe.",actionCode:"Plane heute eine bewusste Pause, die nicht verdient werden muss."}
};
ICS.musterErkennen=text=>ICS.bestesErgebnis(text,ICS.MUSTER);
ICS.musterErkennenAlle=text=>ICS.ergebnisse(text,ICS.MUSTER).slice(0,3);
