window.ICS=window.ICS||{};
ICS.normalisiere=function(text){return String(text||"").toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^\p{L}\p{N}\s]/gu," ").replace(/\s+/g," ").trim();};
ICS.wortliste=function(text){return ICS.normalisiere(text).split(" ").filter(Boolean);};
ICS.phraseGefunden=function(text,phrase){const tw=ICS.wortliste(text),pw=ICS.wortliste(phrase);if(!pw.length)return false;let p=0;for(const w of tw){if(w===pw[p]){p++;if(p===pw.length)return true;}}return false;};
ICS.begriffGefunden=function(text,begriff){const b=ICS.normalisiere(begriff);if(!b)return false;if(b.includes(" "))return ICS.phraseGefunden(text,b);return (" "+ICS.normalisiere(text)+" ").includes(" "+b+" ");};
ICS.trefferAnzahl=function(text,begriffe){return (begriffe||[]).reduce((s,b)=>s+(ICS.begriffGefunden(text,b)?Math.max(1,ICS.wortliste(b).length*2):0),0);};
ICS.ergebnisse=function(text,daten){return Object.keys(daten).map(id=>Object.assign({id,punkte:ICS.trefferAnzahl(text,daten[id].begriffe)},daten[id])).filter(e=>e.punkte>0).sort((a,b)=>b.punkte-a.punkte);};
ICS.bestesErgebnis=function(text,daten){return ICS.ergebnisse(text,daten)[0]||null;};
ICS.escapen=function(text){const d=document.createElement("div");d.textContent=String(text||"");return d.innerHTML;};
ICS.zufall=function(liste){return Array.isArray(liste)&&liste.length?liste[Math.floor(Math.random()*liste.length)]:"";};
